admin-permission: "ezar.sumo"
host-permission: "ezar.sumo.host"
reload: "&e[SUMO] &aConfig reloaded correctly."
noperms: "&cSorry but you do not have permission to execute this command."
host-permission-message: "&eIf you want host a sumo event you need to be vip. &dhttps://store.ezar.it"
nospawnpointset: "&cYou need to set the Lobby & Spawn locations first."
setlobby: "&e[SUMO] &aSumo lobby has been set correctly."
spawnpoint1: "&e[SUMO] &aPlayer spawn point 1 has been set correctly."
spawnpoint2: "&e[SUMO] &aPlayer spawn point 2 has been set correctly."
specpoint: "&e[SUMO] &aPlayer spectate point has been set correctly."
already-on: "&cEvent already on."
noevent: "&aThere are no events hosted."
alreadyin: "&cYou are already in the sumo event."
eliminated: "Â§cYou have been eliminated."
broadcastElimination: "&e(Event) &c%looser% &7has been eliminated by &a%winner%"
winner: "&e(Event) &aWinner: %winner%"
joining: "&aJoining the sumo event.."
in-game: "&eThe event is started."
not-enough-players: "&cNo enough players in the event."
leaveitem: "&cLeave event &7(Left click)"
leaveitem-position: 9
time: 60
times: [45, 30, 15, 10, 5, 4, 3, 2, 1]
broadcast-time: "&9%host% &eStarted &aSumo &eevent is going to begun in &b%time%s &7Type %join%"
admin-help-command:
  - "&aSumo Admin Help"
  - " &7* &6/sumo setlobby &8- &fSets player lobby/spectating point"
  - " &7* &6/sumo setspawn 1/2 &8- &fSets player spawn point"
  - " "
  - " &7* &6/sumo host &8- &fHosts the sumo event"
  - " &7* &6/sumo join &8- &fJoins into the sumo event"
  - " &7* &6/sumo leave &8- &fLeaves the sumo event"
help-command:
  - "&aSumo Help"
  - " &7* &6/sumo host &8- &fHosts the sumo event"
  - " &7* &6/sumo join &8- &fJoins into the sumo event"
match-info:
  - "&eStartig event match. &a(%player1% vs %player2%)"
prematch-countdown: 5
prematch-message: "&e(Event) &7Selecting random players..."
match-countdown: 3
match-countdown-message: "&eThe match starts in &a%time%&e..."
match-started: "&aThe match has started good luck!"